# Generated by Django 5.1 on 2024-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mainGoals', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=5000)),
                ('language', models.CharField(blank=True, max_length=5000)),
                ('ownerId', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
