# Generated by Django 5.0.6 on 2024-09-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistantId', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500000)),
            ],
        ),
    ]
