# Generated by Django 5.0.6 on 2024-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_rename_messageforteaching_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistantId', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500000)),
            ],
        ),
    ]
