# Generated by Django 5.0.6 on 2024-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_knowledgebaseinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='context',
            field=models.CharField(default='teach', max_length=200),
            preserve_default=False,
        ),
    ]
